/* ===========================================================================
   SERVICE WORKER — Mafisa
   Generated by tools/deploy.py. Do not edit a deployed copy.

   Why this exists: data is expensive in Lesotho and signal is patchy outside
   Maseru. Without this, every visit re-downloads the whole app over a
   connection somebody is paying for by the megabyte, and a person with no bars
   sees nothing at all.

   ONE RULE THAT IS NOT AN OPTIMISATION: nothing under /storage/ is ever
   cached. Those are signed links to national IDs, title deeds and trade
   certificates. A cached copy of somebody's ID sitting in a browser is exactly
   the failure this platform cannot have.
   =========================================================================== */
const VERSION = '41c2d8a6a0de';
const SHELL = 'shell-' + VERSION;
const SHELL_FILES = ["./", "./index.html", "./manifest.webmanifest", "icons/mafisa-192.png", "icons/mafisa-512.png", "core/config.js", "core/i18n.js", "core/seed.js", "core/mend.js", "core/ui.js", "strings.js"];

self.addEventListener('install', (e) => {
  // Deliberately NOT cache.addAll: addAll rejects as a unit, so one missing file
  // fails the whole install and the app silently has no offline support at all.
  // Cache what is there, and let a gap be a gap.
  e.waitUntil(
    caches.open(SHELL).then((c) => Promise.all(
      SHELL_FILES.map((f) => c.add(f).catch((err) => {
        console.warn('[sw] could not precache', f, err && err.message);
      }))
    )).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== SHELL).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', (e) => { if (e.data === 'skip-waiting') self.skipWaiting(); });

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;                      // writes go through the outbox
  const url = new URL(req.url);

  // NEVER cache a private document. Not on any path, not under any condition.
  if (url.pathname.includes('/storage/')) return;

  // The API is live data. Try the network; if it fails, the app falls back to
  // its own cache in localStorage and SAYS it is doing so.
  if (url.pathname.startsWith('/rest/') || url.pathname.startsWith('/auth/')) return;

  // Fonts: cache hard. They never change and they are the biggest single
  // download on a first visit.
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(
      caches.open(SHELL).then((c) =>
        c.match(req).then((hit) => hit || fetch(req).then((res) => {
          if (res.ok) c.put(req, res.clone());
          return res;
        }).catch(() => hit)))
    );
    return;
  }

  if (url.origin !== self.location.origin) return;

  // THE APP SHELL.
  //
  // This used to be cache-first — serve the stored copy at once, refresh behind
  // it. That is right for an asset and wrong for a navigation, and it is how
  // four retired subdomains went on serving a pre-fix app to everyone who had
  // ever opened them: the cached page won, and the page that would have
  // redirected them was only ever written into the cache for next time.
  //
  // A navigation now races the network with a short timeout. On a cheap phone
  // with no signal the timeout fires and the cached shell appears as before, so
  // nothing is lost offline. With signal, the person gets the page that is
  // actually being served — which is the only way a deploy can ever reach them.
  const NAV_TIMEOUT = 2500;
  e.respondWith(
    caches.open(SHELL).then((c) =>
      c.match(req, { ignoreSearch: true }).then((hit) => {
        const live = fetch(req).then((res) => {
          if (res.ok) c.put(req, res.clone());
          return res;
        });
        if (!hit) return live.catch(() => c.match('./index.html'));
        return Promise.race([
          live.catch(() => hit),
          new Promise((resolve) => setTimeout(() => resolve(hit), NAV_TIMEOUT))
        ]);
      }))
  );
});
